name: on-commit-build
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    test:
        name: Run the build process and ensure proper build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v7
            - name: Setup node version
              uses: actions/setup-node@v7
              with:
                  node-version: '26'
            - name: Install project dependencies
              run: npm install
            - name: Build the project
              run: npm run build
              env:
                  CI: true
